
language: node_js
node_js:
  - v8

script: echo "npm test temporarily disabled"

before_deploy: 
  - "echo 'Before Deploy'"
  - npm i -g @oclif/dev-cli rimraf
  - npm i

deploy:
  provider: npm
  email: "maordavidov@gmail.com"
  api_key: $NPM_TOKEN
  on:
    tags: false

after_deploy: "echo 'After Deploy'"