language: node_js
node_js:
  - v8

cache: 'npm'

script:
  - .\bin\run --version
  - .\bin\run --help
  - 'npm' run test

deploy:
  provider: npm
  email: "maordavidov@gmail.com"
  api_key: $NPM_TOKEN
  on:
    tags: false

after_deploy: "echo 'After Deploy'"